// <auto-generated />
namespace MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Edit01 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Edit01));
        
        string IMigrationMetadata.Id
        {
            get { return "202006261521185_Edit01"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
